sticker_list = ["CAACAgQAAxkBAAICTGX4oj1EVy5zATCn2lw4PQUPz7vhAAKaFwACpvFxHs9ZRtDBeIxDNAQ",
                "CAACAgIAAxkBAAICTmX4omw6E3tqrOMZMTRvMeqBOpcqAAJpHgACHe1hSSl1ko95EAL",
                "CAACAgIAAxkBAAICUGX4opYgXb8ygnxrH1kIDuw-R_Z8AAJ-GQAC9LigSW1WKDwgc2U_NAQ",
                "CAACAgIAAxkBAAICVGX4otwTz9syfFWnJJZ5r1JxU84UAAKLFQACvYzxS0ySmLTCdQV6NAQ",
                "CAACAgIAAxkBAAICVmX4owZCjf90HKjR1svvSlbqs_StAAKeFwACpmbpSeMeZ7i4jpMoNAQ",
                "CAACAgIAAxkBAAICWGX4oxhFbnARS8-bPsPYJbFJWebxAAKeFwACnbzhSQbQcN_mxpdJNAQ",
                "CAACAgIAAxkBAAICWmX4ozltlpWAPwMBbPVDYA6Swx_SAALvJAACfy2RSN7sKkUmnd2WNAQ",
                "CAACAgIAAxkBAAICXGX4o1ZZnplv_TVIfhKLsFiOCvwXAAJTFgAC_ONBSY5DRFRhEBTWNAQ",
                "CAACAgIAAxkBAAICXmX4o4MF5B0uEuWaL87cKR6Ow5gqAALgHAACdtBxS_KzA-uoogSDNAQ",
                "CAACAgIAAxkBAAICYGX4o5JyStdN2jt9G1DGLmgwgtVrAAIiEwACMZVBScO6foNAo9ZBNAQ"]
dictionary = {1: "winter",
              2: "winter",
              3: "spring",
              4: "spring",
              5: "spring",
              6: "summer",
              7: "summer",
              8: "summer",
              9: "autumn",
              10: "autumn",
              11: "autumn",
              12: "winter"}
